/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fpqin' at '14-11-20 下午5:39' with Gradle 2.0
 *
 * @author fpqin, @date 14-11-20 下午5:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
